version: "3"

tasks:
  frontend:
    dir: "{{.USER_WORKING_DIR}}/frontend"
    cmds:
      - npm install
      - npm run build

  test:
    cmds:
      - go test ./...

  run_pprof:
    deps:
      - frontend
    cmds:
      - go run -tags pprof,dev .
      - go run tools/merge_pprofs.go -root build/cpu_profiles/hosts -o build/cpu_profiles/merged.pprof
    summary: |
      Runs the application with CPU profiling enabled.
      Merges all existing profiles afterwards into build/cpu_profiles/merged.pprof which is used for building.
