version: "3"

tasks:
  frontend:
    dir: "{{.USER_WORKING_DIR}}/frontend"
    cmds:
      - npm install
      - npm run build

  test:
    cmds:
      - go test ./...

  run_pprof:
    cmds:
      - go run -tags pprof,dev .

  merge_pprofs:
    cmds:
      - go run tools/merge_pprofs.go -root build/cpu_profiles/hosts -o build/cpu_profiles/merged.pprof
